//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookS.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class books
    {
        public int id { get; set; }
        public string title { get; set; }
        public string author { get; set; }
        public string category { get; set; }
        public string quantity { get; set; }
        public string price { get; set; }
    
        public virtual category category1 { get; set; }
    }
}
